import sqlite3, uuid
from pathlib import Path

DB = Path.home() / 'Library' / 'Group Containers' / '72KVKW69K8.com.hindsightlabs.paprika.mac.v3' / 'Data' / 'Database' / 'Paprika.sqlite'

VARIANTS = [
    ('a alloro', 13), ('a salvia', 25), ('a bunch of fresh coriander', 25),
    ('acciughe salate', 16), ('acqua oligominerale naturale', 19),
    ("albumi d'uovo", 24), ('ale', 21), ('amberi', 16),
    ('ambi di sedano', 25), ('ambi sedano', 25), ('ambo di sedano', 25), ('ambo sedano', 25),
    ('anchovy fillets in oil', 16), ('arancia )', 25), ('arge onion', 25), ('arlic cloves', 25),
    ('bacca di vaniglia', 13), ('baccello vaniglia', 13), ('bacche cardamomo', 13),
    ('bacche ginepro', 13), ('baking soda', 15), ('banane', 25),
    ('bay leaf', 13), ('bay leaves', 13), ('biancostato di vitello', 6),
    ('black pepper', 13), ('bulb of fennel', 25), ('bunch radishes', 25),
    ('bustine vanillina', 13), ('bustine zafferano', 13),
    ('cacao amaro in polvere', 15), ('caciocavallo )', 24), ('calamaro', 16),
    ('cannella in polvere', 13), ('cannella macinata', 13), ('canola oil', 4),
    ('carcassa di pollo', 6), ('carcasse di pollo', 6),
    ('carne di maiale macinata', 6), ('carne di manzo macinata', 6),
    ('carne di vitello a fette', 6), ('carote', 25), ('carrot', 25),
    ('carrots', 25), ('carrots )', 25), ('ceci secchi', 8), ('celeriac', 25),
    ('celery', 25), ('celery rib', 25), ('cespi lattuga', 25),
    ('cespo broccoli', 25), ('cespo insalata scarola riccia', 25),
    ('cestini lamponi', 25), ('cestino lamponi', 25), ('cestini more', 25),
    ('cestino fragole', 25), ('cestino mirtilli', 25), ('cheddar cheese', 24),
    ('chopped fresh cilantro', 25), ('chopped fresh or canned tomato', 25),
    ('chopped onions', 25), ('chopped potatoes', 25),
    ('cioccolato a scagliette', 15), ('cioccolato fondente 70%', 15),
    ('cipolla bionda', 25), ('cipolle', 25), ('cipolle )', 25),
    ('cipolle bianche', 25), ('cipolle rosse', 25),
    ('cipollina novella', 25), ('cipolline', 25), ('cipollotto fresco', 25),
    ('ciuffi prezzemolo', 25), ('ciuffo prezzemolo', 25),
    ('ciuffi salvia', 25), ('ciuffo basilico', 25),
    ('corn on the cob', 25), ('costa di sedano', 25), ('costa di sedano verde', 25),
    ('coste di sedano verde', 25), ('costola sedano', 25), ('costole sedano', 25),
    ('costata di manzo', 6), ('cozze pulite', 16),
    ('crema pasticcera al cioccolato', 24), ('cubetto lievito di birra', 15),
    ('diced stewing beef', 6), ('dischi pasta sfoglia fresca rustica', 15),
    ('dried red lentils', 8), ('duck fat', 4), ('duck legs', 6),
    ('farina semola', 15), ('farina tipo 0', 15), ('farina tipo 0 )', 15),
    ('farina tipo 00', 15), ('fave secche', 8), ('fegati di pollo', 6),
    ('fettine vitello', 6), ('fichi secchi tritati', 15),
    ('filetti di acciughe sottolio', 16), ('filetti di baccalà', 16),
    ('filetti di merluzzo', 16), ('filetti di tonno', 16),
    ('filetto di acciuga sottolio', 16), ('filetto merluzzo', 16),
    ('filetto salmone', 16), ('finocchi', 25),
    ('fogli di ostia alimentare', 7), ('foglie basilico', 25),
    ('foglie menta', 25), ('foglie mentuccia', 25), ('foglie salvia', 25),
    ('fondo di pesce', 9), ('fondo di verdure arrostite', 9),
    ('formaggio di capra fresco', 24), ('fresh lemon juice', 25),
    ('fresh red chilli', 25), ('gamberetti piccoli', 16),
    ('gambi di prezzemolo', 25), ('gambi di sedano', 25), ('garlic', 25),
    ('gelato alla vaniglia', 7), ('generous 1/2 teaspoon turmeric powder', 13),
    ('girello intero', 6), ('good extra virgin olive oil', 4), ('ground cumin', 13),
    ('handful chopped fresh cilantro leaves', 25), ('handful small beetroot leaves', 25),
    ('ime', 25), ('imone', 25), ('imone spremuto', 25), ('imoni', 25),
    ('insalata scarola riccia', 25), ('latte fresco', 24), ('latte intero', 24),
    ('lentils', 8), ('lievito di birra di lievito naturale secco', 15),
    ('lievito madre rinfrescato', 15), ('lonza di maiale tritata', 6),
    ('magliette di maccheroncino', 8), ('mandorle spellate e tritate', 15),
    ('marmellata a piacere', 15), ('masoor dal red lentils', 8),
    ('mazzo cipollotti', 25), ('medium tomatoes', 25), ('melanzana', 25),
    ('miele di castagne', 15), ('milk', 24), ('milk or water', 24),
    ('mollica di pane', 17), ('muscolo di bovino adulto', 6), ('muscolo di vitello', 6),
    ('natural yoghurt', 24), ('ni aceto bianco', 4), ('ni brandy', 21),
    ('ni crème fraîche', 24), ('ni curry', 13), ('ni latte scremato in polvere', 24),
    ('ni sale', 13), ('ni salsa di menta', 9), ('ni senape inglese', 13),
    ('ni vanillina', 13), ('ni vermuth', 21), ('ni zucchero', 15),
    ('no brandy', 21), ('no cannella', 13), ('no capperi', 9),
    ('no chiodi di garofano', 13), ('no curry', 13), ('no di lievito vanigliato', 15),
    ('no marsala stravecchio', 21), ('no miele', 15), ('no sale', 13),
    ('no semi di finocchio', 13), ('no senape inglese', 13),
    ('no vino bianco secco', 21), ('no vino dolce', 21), ('no vino madera', 21),
    ('no vino porto', 21), ('no vino rosso secco', 21), ('no zucchero', 15),
    ('noce burro', 24), ('noci tritate', 15), ('o aglio', 25),
    ('of an iceberg lettuce', 25), ('olio', 4), ('olio e sale grosso per la superficie', 4),
    ('olio extravergine di oliva', 4), ('olive oil', 4),
    ('olive verdi in salamoia', 20), ('onion', 25), ('onions', 25),
    ('ossi misti di vitello', 6), ('osso di manzo con midollo', 6),
    ('osso di vitello', 6), ('oves garlic', 25), ('oves of garlic', 25),
    ('pan grattato condito', 17), ('pancetta tesa affumicata', 6),
    ('pane pugliese', 17), ('pangrattato condito alla messinese', 17),
    ('panna fresca liquida', 24), ('paprica dolce', 13),
    ('parmigiano reggiano dop grattugiato', 24), ('parsley', 25),
    ('parte burro', 24), ('parte farina tipo 00', 15),
    ('pasta di semola rigata', 8), ('pasta frolla leggera', 15),
    ('pasta sfoglia fresca', 15), ('patata', 25), ('patate rosse', 25),
    ('pecorino grattugiato', 24), ('pecorino pepato siciliano', 24),
    ('pelati', 9), ('pepe', 13), ('pepe bianco in grani', 13),
    ('pepe nero in grani', 13), ('pepe nero macinato', 13),
    ('peperoncini', 25), ('peperoni rossi', 25), ('petti di pollo', 6),
    ('piece ginger', 13), ('piselli freschi sgranati', 25),
    ('pistachio nuts', 15), ('pizzichi pepe', 13), ('pizzichi sale', 13),
    ('pizzico vaniglia', 13), ('polpa di carne trita', 6),
    ('polpa di vitellone macinata', 6), ('pomodori maturi', 25),
    ('pomodori secchi sottolio', 9), ('pomodorini ciliegia', 25),
    ('pomodorini ciliegini', 25), ('pomodorini freschi', 25),
    ('pomodorini pachino', 25), ('pomodoro concentrato', 9),
    ('pomodoro maturo', 25), ('porro', 25), ('prezzemolo tritato', 25),
    ('prosciutto cotto a fette', 6), ('provola dolce', 24),
    ('prugne snocciolate', 25), ('pugni olive verdi', 20),
    ('punta concentrato di pomodoro', 9), ('q.b. noce moscata', 13),
    ('q.b. pane a cassetta', 17), ('q.b. sale', 13), ('q.b. sale e pepe', 13),
    ('q.b. strutto', 4), ('q.b. tartufo bianco', 7),
    ('q.b. zucchero', 15), ('q.b. zucchero a velo', 15),
    ('rafano fresco', 25), ('ragout di pesce', 16),
    ('red onion', 25), ('red pepper', 25), ('rhum', 21), ('rhum chiaro', 21),
    ('ricotta di pecora', 24), ('ricotta romana', 24),
    ('riso semifino', 8), ('riso vialone', 8),
    ('romanesco or white cauliflower', 25), ('rosemary', 25),
    ('rotolo pasta sfoglia', 15), ('salame )', 6), ("salse per l'arrosto", 9),
    ('salt', 13), ('salt and pepper', 13), ("scorza di un'arancia", 25),
    ('sea salt', 13), ('serrano chile', 25), ('small raw beetroots', 25),
    ('small wholemeal flour tortillas', 17), ("soffritto all'italiana con pancetta", 7),
    ('soffritto di cipolle', 7), ('sourdough toast', 17), ('spalla di vitello', 6),
    ('sprig of fresh coriander', 25), ('sprigs thyme', 25), ('spring onions', 25),
    ('stecca cioccolato fondente 70%', 15), ('stick celery', 25),
    ('sticks sticks of celery', 25), ('stinchi di maiale', 6),
    ('stoccafisso norvegese', 16), ('sultanas', 25),
    ('t acqua', 19), ('t acqua oligominerale naturale', 19),
    ('t brodo di pesce', 9), ('t brodo di verdure', 9),
    ('t brodo universale', 9), ('t brodo vegetale', 9),
    ('t crema al cioccolato', 24), ('t latte', 24),
    ('t olio per friggere', 4), ('t panna', 24),
    ('tablespoon canola oil', 4), ('tablespoon vegetable oil', 4),
    ('tablespoons chopped fresh parsley', 25), ('tablespoons fresh lemon juice', 25),
    ('tablespoons good white wine vinegar', 4), ('tablespoons peanut butter', 9),
    ('tablespoons plain flour', 15), ('taglierine', 8),
    ('tazza farina', 15), ('tazza latte', 24),
    ('teaspoon black mustard seeds', 13), ('teaspoon cumin seeds', 13),
    ('teaspoon ground cumin', 13), ('teaspoon paprika or bafaat powder', 13),
    ('teaspoon salt', 13), ('teaspoon shallot vinegar', 4),
    ('teaspoon sweet smoked paprika', 13), ('teaspoon turmeric', 13),
    ('teaspoons baking powder', 15), ('teaspoons ground cumin', 13),
    ('testa aglio', 25), ('teste e gusci di crostacei', 16),
    ('tomatoes', 25), ('tomatoes. chopped', 25), ('tracchiolelle di maiale', 6),
    ('trancio tonno', 16), ("tuorli d'uovo", 24), ('tuorlo', 24),
    ('turmeric', 13), ('uacamole', 9),
    ('un cespo di lattuga scarola riccia', 25),
    ('uova intere', 24), ('uovo', 24),
    ('uvetta fatta rinvenire poi strizzata e infarinata', 25),
    ('vegetable broth or 1182.95 ml water', 9),
    ('vino marsala secco', 21), ('vongole spurgate', 16),
    ('x 150g skinless free-range chicken breast', 6),
    ('young carrots', 25), ('zucchero cristallizzato', 15),
    ('zucchero semolato', 15), ('zucchina lunga siciliana', 25),
    ('1/2 cucchiaino sale fino', 13), ('1/2 cups chicken broth', 9),
    ('1/2 g buccia di arancia', 25), ('1/2 g buccia di limone', 25),
    ('1/2 lt passata di pomodoro', 9), ('1/2 tablespoons olive oil', 4),
    ('1/2 uova', 24), ('1/4 teaspoons ground cumin', 13),
    ('lievito vanigliato', 15), ('salsa di menta', 9),
    ('latte scremato in polvere', 24), ("grasso d'anatra", 4),
    # "o X" variants
    ('o capperi sotto sale', 9), ('o concentrato di pomodoro', 9),
    ('o crème fraîche', 24), ('o di cacao amaro in polvere', 15),
    ('o farina', 15), ('o miele', 15), ('o paprica dolce', 13),
    ('o parmigiano', 24), ('o pinoli', 15), ('o scalogno', 25),
    ('o uva sultanina', 25), ('o zucchero', 15), ('o zucchero di canna', 15),
    ('pezzi stoccafisso norvegese', 16),
    ('marie', 17),
]

con = sqlite3.connect(str(DB))
con.row_factory = sqlite3.Row
cur = con.cursor()

cur.execute("SELECT ZNAME FROM ZGROCERYINGREDIENT")
existing = {r[0].lower() for r in cur.fetchall()}
cur.execute("SELECT Z_MAX FROM Z_PRIMARYKEY WHERE Z_NAME='GroceryIngredient'")
next_pk = cur.fetchone()[0] + 1

inseriti = saltati = 0
for name, aisle_pk in VARIANTS:
    if name.lower() in existing:
        saltati += 1
        continue
    uid = str(uuid.uuid4()).upper()
    cur.execute(
        "INSERT INTO ZGROCERYINGREDIENT (Z_PK,Z_ENT,Z_OPT,ZISSYNCED,ZAISLE,ZNAME,ZSTATUS,ZUID) VALUES (?,4,1,0,?,?,'new',?)",
        (next_pk, aisle_pk, name, uid)
    )
    existing.add(name.lower())
    next_pk += 1
    inseriti += 1

cur.execute("UPDATE Z_PRIMARYKEY SET Z_MAX=? WHERE Z_NAME='GroceryIngredient'", (next_pk-1,))
con.commit()
con.close()
print(f"✅ Inseriti: {inseriti} varianti | Saltati (già presenti): {saltati}")
print(f"   Totale ingredienti nel dizionario: {len(existing)}")
